language: java
install: true
addons:
  ssh_known_hosts: 5.196.65.205
  apt:
    packages:
    - sshpass
cache:
  directories:
  - $HOME/.m2
script:
- mvn package
after_success:
- RELEASE=`cat pom.xml | grep "^    <version>.*</version>$" | awk -F'[><]' '{print $3}'`
# Update official "cerise-server-mock" image.
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push $DOCKER_USERNAME/cerise-server-mock
# Run "cerise" image on reference server.
- sshpass -p $SSH_PASSWORD ssh ci@5.196.65.205 'docker stop $(docker ps -aq --filter "label=cerise")'
- sshpass -p $SSH_PASSWORD ssh ci@5.196.65.205 'docker rm -f $(docker ps -aq --filter "label=cerise")'
- sshpass -p $SSH_PASSWORD ssh ci@5.196.65.205 "docker pull straumat/cerise-server-mock:$RELEASE"
- sshpass -p $SSH_PASSWORD ssh ci@5.196.65.205 "nohup docker run -l cerise -p 80:8080 straumat/cerise-server-mock:$RELEASE > /home/ci/cerise-server-mock.logs &"